# Generated by Django 3.2.8 on 2021-10-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactlist',
        ),
    ]
