# Generated by Django 3.2.8 on 2021-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='address',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
